pipeline {
    agent any
    stages {
        stage('Setup') {
            steps {
                sh "./jenkins/setup.sh"
            }
        }
        stage('Test') {
            steps {
                sh "./jenkins/setup.sh"
            }
        }
        stage('Build') {
            steps {
                sh "./jenkins/setup.sh"
            }
        }
        stage('Push') {
            steps {
                sh "./jenkins/setup.sh"
            }
        }
        stage('Deploy') {
            steps {
                sh "./jenkins/setup.sh"
            }
        }
    }
}